name       : libodfgen
version    : 0.1.7
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/libwpd/libodfgen/libodfgen-0.1.7/libodfgen-0.1.7.tar.xz : 323e491f956c8ca2abb12c998e350670930a32317bf9662b0615dd4b3922b831
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : Library for generating documents in ODF
description: |
    libodfgen is a library for generating documents in Open Document Format (ODF). It provides generator implementations for all document interfaces supported by librevenge:
    * text documents
    * vector drawings
    * presentations
    * spreadsheets
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
