name       : libodfgen
version    : 0.1.6
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/libwpd/libodfgen/libodfgen-0.1.6/libodfgen-0.1.6.tar.xz : 03b210ab44f05e38091508cdca6ba0ff73de3ea8a168f849b8f1c5059c20b9e9
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Library for generating documents in ODF
description: |
    libodfgen is a library for generating documents in Open Document Format (ODF). It provides generator implementations for all document interfaces supported by librevenge:
    * text documents
    * vector drawings
    * presentations
    * spreadsheets
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
